#!/usr/bin/env node
// Regenerates THIRD_PARTY_NOTICES.md from `cargo tree`, `cargo metadata` and the license files
// inside each crate's published source. Node 24, no npm dependencies.
//
//   node tools/gen-notices.mjs           rewrite THIRD_PARTY_NOTICES.md
//   node tools/gen-notices.mjs --check   exit 1 if the file is out of date (writes nothing)
//
// The crate set is the union, over the release targets below, of what `cargo tree` shows
// `crumple-cli` reaching through normal and build dependencies. Crates whose package ships no
// license file get their text from tools/notices/ (see tools/notices/sources.json); a crate
// with neither fails the run. The bundled C and assembly sections name files inside the `-sys` crates, so
// a dependency bump that moves those files also fails the run instead of dropping a notice.

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = join(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = join(repo, 'THIRD_PARTY_NOTICES.md');
const extraDir = join(repo, 'tools', 'notices');
const ROOT = 'crumple-cli';
const TARGETS = ['x86_64-pc-windows-msvc', 'x86_64-unknown-linux-gnu', 'aarch64-apple-darwin'];
const LICENSE_FILE = /^(licen[cs]e|copying|unlicense|copyright)/i;

// --- crate graph ----------------------------------------------------------------
// `cargo tree` applies the real feature resolver (cargo metadata's resolve unifies features
// across dev-dependencies and targets, and would list crates that are never built), and
// `cargo metadata` supplies each crate's source directory.
const run = (args) => execFileSync('cargo', args, { cwd: repo, encoding: 'utf8', maxBuffer: 512 << 20 });
const meta = JSON.parse(run(['metadata', '--format-version', '1', '--locked']));
const workspace = new Set(meta.workspace_members);
const byKey = new Map(meta.packages.filter((p) => !workspace.has(p.id)).map((p) => [`${p.name} ${p.version}`, p]));
const reached = new Set();
for (const triple of TARGETS) {
  const out = run(['tree', '--locked', '-p', ROOT, '-e', 'normal,build', '--target', triple, '--prefix', 'none', '--format', '{p}']);
  for (const line of out.split('\n')) {
    const m = line.match(/^(\S+) v(\S+)/);
    if (m && byKey.has(`${m[1]} ${m[2]}`)) reached.add(`${m[1]} ${m[2]}`);
  }
}
const cmp = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
const deps = [...reached].map((k) => byKey.get(k))
  .sort((a, b) => cmp(a.name, b.name) || cmp(a.version, b.version));
const dirOf = (name) => {
  const hits = deps.filter((p) => p.name === name);
  if (hits.length !== 1) throw new Error(`expected exactly one ${name} in the graph, found ${hits.length}`);
  return { dir: dirname(hits[0].manifest_path), version: hits[0].version };
};

// --- text helpers ----------------------------------------------------------------
// Most license files are UTF-8; a few (rav1e's PATENTS) are Windows-1252.
function text(path) {
  const buf = readFileSync(path);
  let s;
  try { s = new TextDecoder('utf-8', { fatal: true }).decode(buf); } catch { s = new TextDecoder('windows-1252').decode(buf); }
  return s.replace(/^﻿/, '').replace(/\r\n?/g, '\n').replace(/[ \t]+$/gm, '').trim();
}
const file = (name, ...rel) => {
  const p = join(dirOf(name).dir, ...rel);
  if (!existsSync(p)) throw new Error(`${name}: ${rel.join('/')} not found; update tools/gen-notices.mjs`);
  return text(p);
};
const block = (t) => '```text\n' + t + '\n```\n';
// The license comment at the top of a source file, without its comment markers.
function header(name, rel, from, to) {
  const src = file(name, ...rel);
  const m = src.match(new RegExp(`${from}[\\s\\S]*?${to}`));
  if (!m) throw new Error(`${name}: license header not found in ${rel.join('/')}`);
  return m[0].split('\n').map((l) => l.replace(/^\s*(?:;\*|\*|;|\/\/)\s?/, '')).join('\n').trim();
}
const v = (name) => dirOf(name).version;

// --- hand-written sections: code that cargo-deny cannot see ---------------------------
let o = `# Third-party notices

Crumple is Apache-2.0 (see \`LICENSE\` and \`NOTICE\`). This file lists the third-party code that
the \`crumple\` binary is built from. It is generated by \`node tools/gen-notices.mjs\` from
\`cargo tree\`, \`cargo metadata\` and the license files inside each crate's published source; do
not edit it by hand. The crate list is every crate that \`crumple-cli\` reaches through normal and
build dependencies on these targets:
${TARGETS.map((t) => `\`${t}\``).join(', ')}.
It therefore also includes build-time tools and proc-macro crates (\`cc\`, \`nasm-rs\`, \`syn\`,
...) that are not linked in.

## Bundled C and assembly code and other key components

\`cargo-deny\` cannot see C and assembly sources bundled inside crates, so these are listed first.

### SSIMULACRA2 (\`ssimulacra2\` ${v('ssimulacra2')}, BSD-2-Clause)

\`crumple-metric\` ports code from this crate (see \`crates/crumple-metric/LICENSE-ssimulacra2\`).
The SSIMULACRA2 algorithm and its weights were designed by Jon Sneyers (Cloudinary); the
reference implementation lives in libjxl.

${block(file('ssimulacra2', 'LICENSE'))}
### libwebp (bundled in \`libwebp-sys\` ${v('libwebp-sys')}, BSD-3-Clause plus patent grant)

\`libwebp-sys\` declares only MIT for its Rust code; the vendored libwebp C sources carry this license:

${block(file('libwebp-sys', 'vendor', 'COPYING'))}
Additional IP rights grant (libwebp \`PATENTS\`):

${block(file('libwebp-sys', 'vendor', 'PATENTS'))}
### mozjpeg / libjpeg-turbo / IJG (bundled in \`mozjpeg-sys\` ${v('mozjpeg-sys')}, IJG AND BSD-3-Clause AND Zlib)

This software is based in part on the work of the Independent JPEG Group.

${block(file('mozjpeg-sys', 'LICENSE'))}
Some libjpeg-turbo SIMD extensions bundled in \`mozjpeg-sys\` are under the zlib License, for example:

${block(header('mozjpeg-sys', ['vendor', 'simd', 'arm', 'aarch64', 'jchuff-neon.c'], "This software is provided 'as-is'", 'source distribution\\.'))}
### libdeflate (bundled in \`libdeflate-sys\` ${v('libdeflate-sys')}, MIT; used by oxipng)

${block(file('libdeflate-sys', 'libdeflate', 'COPYING'))}
### rav1e ${v('rav1e')} (AV1 encoder inside ravif, BSD-2-Clause plus AOMedia Patent License 1.0)

${block(file('rav1e', 'LICENSE'))}
${block(file('rav1e', 'PATENTS'))}
Some rav1e source and assembly files carry other copyright lines under the same BSD-2-Clause
terms: "Copyright (c) 2001-2016, Alliance for Open Media" and "Copyright © 2018-2021, VideoLAN and
dav1d authors". Its \`x86inc.asm\` is from x264 (ISC, below).

### rav1d ${v('rav1d')} (AV1 decoder inside avif-decode, BSD-2-Clause; port of dav1d)

${block(file('rav1d', 'COPYING'))}
The AOMedia Patent License 1.0 reproduced under rav1e above also covers AV1 decoding.

### x86inc.asm (x264 project, ISC; bundled in rav1e and rav1d)

${block(header('rav1e', ['src', 'ext', 'x86', 'x86inc.asm'], 'Copyright \\(C\\)', 'USE OR PERFORMANCE OF THIS SOFTWARE\\.'))}
### avif-parse ${v('avif-parse')} (MPL-2.0, used unmodified)

Source code: https://crates.io/crates/avif-parse/${v('avif-parse')} (repository https://github.com/kornelski/avif-parse).
Crumple uses this crate unmodified; its source files are available under the MPL-2.0 at that address.

${block(file('avif-parse', 'LICENSE'))}
### oxipng ${v('oxipng')} (MIT)

${block(file('oxipng', 'LICENSE'))}
## All Rust crates

| Crate | Version | License (as declared) |
|---|---|---|
${deps.map((d) => `| ${d.name} | ${d.version} | ${d.license ?? '(none declared)'} |`).join('\n')}

## License texts shipped with each crate

Identical texts are printed once, followed by the crates that ship them.

`;

// --- per-crate license files ------------------------------------------------------------
const extra = JSON.parse(readFileSync(join(extraDir, 'sources.json'), 'utf8'));
const problems = [];
const groups = new Map();
const fromRepo = [];
for (const d of deps) {
  const dir = dirname(d.manifest_path);
  let files = readdirSync(dir).filter((f) => LICENSE_FILE.test(f)).sort(cmp).map((f) => [f, join(dir, f)]);
  if (!files.length) {
    const e = extra[d.name];
    if (!e) { problems.push(`${d.name} ${d.version} ships no license file and has no entry in tools/notices/sources.json`); continue; }
    if (e.version !== d.version) problems.push(`${d.name}: tools/notices was checked for ${e.version}, the graph has ${d.version}; re-check ${e.source}`);
    files = readdirSync(join(extraDir, e.dir)).sort(cmp).map((f) => [f, join(extraDir, e.dir, f)]);
    fromRepo.push(`- **${d.name} ${d.version}** (${d.license}): ${e.note} Source: ${e.source} at commit \`${e.commit}\`.`);
  }
  for (const [f, p] of files) {
    const t = text(p);
    const h = createHash('sha256').update(t).digest('hex');
    if (!groups.has(h)) groups.set(h, { t, crates: [] });
    groups.get(h).crates.push(`${d.name} ${d.version} (${f})`);
  }
}
if (fromRepo.length) {
  o += `These crates ship no license file in their published package. Their texts below were taken from\nthe upstream repository (kept in \`tools/notices/\`):\n\n${fromRepo.join('\n')}\n\n`;
}
for (const g of groups.values()) o += `### ${g.crates.join(', ')}\n\n${block(g.t)}\n`;
o = o.replace(/\n+$/, '\n');

if (problems.length) {
  for (const p of problems) console.error(`error: ${p}`);
  process.exit(1);
}
if (process.argv.includes('--check')) {
  const cur = existsSync(outFile) ? readFileSync(outFile, 'utf8') : '';
  if (cur !== o) { console.error('THIRD_PARTY_NOTICES.md is out of date: run node tools/gen-notices.mjs'); process.exit(1); }
  console.log(`THIRD_PARTY_NOTICES.md is up to date (${deps.length} crates)`);
} else {
  writeFileSync(outFile, o);
  console.log(`wrote THIRD_PARTY_NOTICES.md: ${deps.length} crates, ${groups.size} license texts`);
}
